namenode:
  image: aksw/hadoop-namenode
  hostname: namenode
  container_name: namenode
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/namenode:/hadoop/dfs/name
  environment:
    - CLUSTER_NAME=test
  env_file:
    - ./hadoop.env
  ports:
    - "50070:50070"

datanode1:
  image: aksw/hadoop-datanode
  hostname: datanode1
  container_name: datanode1
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode1:/hadoop/dfs/data
  env_file:
    - ./hadoop.env

datanode2:
  image: aksw/hadoop-datanode
  hostname: datanode2
  container_name: datanode2
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode2:/hadoop/dfs/data
  env_file:
    - ./hadoop.env

spark-master:
  image: aksw/hadoop-spark-master
  hostname: spark-master
  container_name: spark-master
  domainname: hadoop
  net: hadoop
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    - SPARK_CONF_spark_eventLog_enabled=true
    - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
    - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
  env_file:
    - ./hadoop.env
  ports:
      - "8080:8080"

spark-worker:
  image: aksw/hadoop-spark-worker
  hostname: spark-worker
  domainname: hadoop
  net: hadoop
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    - SPARK_CONF_spark_eventLog_enabled=true
    - SPARK_CONF_spark_eventLog_dir=hdfs://namenode:8020/spark-logs
    - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode:8020/spark-logs
    - SPARK_MASTER_URL=spark://spark-master:7077
  env_file:
    - ./hadoop.env

spark-notebook:
  image: aksw/hadoop-spark-notebook
  hostname: sparknotebook
  container_name: sparknotebook
  domainname: hadoop
  net: hadoop
  environment:
    - SPARK_NOTEBOOK_MASTER=yarn-client  
  env_file:
    - ./hadoop.env    
  ports:
    - "9000:9000"
